[package]
name = "world-data-types"
version = "0.1.0"
edition = "2024"

[dependencies]
geo = { version = "0.30.0", features = ["serde", "use-serde"] }
serde = { version = "1.0.219", features = ["derive"] }
